# Setup
title:        Fortnite Gratis
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Fortnite Gratis
  url:        https://fortnitegratis.com.br

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

google_ad_client: your-adsense-code
